/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JevTaggerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/jevClient.ts
var import_obsidian = require("obsidian");
var JevClient = class {
  constructor(apiKey, endpoint = "https://api.typesafe.ai/v1/systemone") {
    this.apiKey = apiKey;
    this.endpoint = endpoint;
  }
  setApiKey(key) {
    this.apiKey = key;
  }
  async evaluateNote(state, tags) {
    if (!this.apiKey) {
      throw new Error("Jev API Key is not configured. Please set it in the plugin settings.");
    }
    const enabledTags = tags.filter((t2) => t2.enabled);
    if (enabledTags.length === 0) {
      return [];
    }
    const questions = {};
    for (const tag of enabledTags) {
      questions[`q_${tag.name}`] = {
        type: "choice",
        instructions: tag.instructions,
        criteria: {
          match: tag.matchCriteria,
          other: tag.otherCriteria
        }
      };
    }
    const payload = {
      model: "jev-latest",
      state,
      questions
    };
    const response = await (0, import_obsidian.requestUrl)({
      url: this.endpoint,
      method: "POST",
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        "Content-Type": "application/json",
        "User-Agent": "obsidian-jev-tagger/1.0"
      },
      body: JSON.stringify(payload)
    });
    if (response.status !== 200) {
      throw new Error(`Jev API Error (${response.status}): ${response.text}`);
    }
    const data = response.json;
    const results = [];
    for (const tag of enabledTags) {
      const ans = data.answers[`q_${tag.name}`];
      if (!ans) continue;
      let matchProb = 0;
      if (ans.probabilities && typeof ans.probabilities.match === "number") {
        matchProb = ans.probabilities.match;
      } else if (ans.choice === "match") {
        matchProb = ans.confidence ?? 1;
      } else {
        matchProb = 0;
      }
      results.push({
        tagName: tag.name,
        probability: matchProb,
        confidence: ans.confidence ?? matchProb,
        isMatch: ans.choice === "match",
        description: tag.matchCriteria
      });
    }
    results.sort((a, b) => b.probability - a.probability);
    return results;
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/batchTagModal.ts
var import_obsidian2 = require("obsidian");

// src/i18n.ts
var LANGUAGES = ["zh", "en"];
var LANGUAGE_OPTIONS = {
  zh: "\u7B80\u4F53\u4E2D\u6587",
  en: "English"
};
var translations = {
  zh: {
    "plugin.ribbon": "Smart Tagger: \u667A\u80FD\u6807\u7B7E\u63A8\u8350",
    "notice.noActiveFile": "\u8BF7\u5148\u5728\u7F16\u8F91\u5668\u4E2D\u6253\u5F00\u4E00\u7BC7\u7B14\u8BB0\u3002",
    "notice.analyzing": "Jev \u6B63\u5728\u5206\u6790\u7B14\u8BB0: {name}...",
    "notice.noEligibleTags": "\u672A\u68C0\u6D4B\u5230\u7F6E\u4FE1\u5EA6 \u2265 {threshold}% \u7684\u65B0\u6807\u7B7E\u3002",
    "notice.autoApplySuccess": "\u5DF2\u6210\u529F\u81EA\u52A8\u8FFD\u52A0 {count} \u4E2A\u9AD8\u7F6E\u4FE1\u6807\u7B7E\uFF01",
    "notice.tagsAlreadyExist": "\u76F8\u5173\u6807\u7B7E\u5747\u5DF2\u5B58\u5728\u4E8E\u7B14\u8BB0\u4E2D\u3002",
    "notice.autoApplyFailed": "\u81EA\u52A8\u6253\u6807\u5931\u8D25: {error}",
    "notice.tagAdded": "\u5DF2\u6DFB\u52A0\u6807\u7B7E #{tag}",
    "notice.applyAllSuccess": "\u5DF2\u6210\u529F\u6DFB\u52A0 {count} \u4E2A\u6807\u7B7E\u5230 Frontmatter\uFF01",
    "notice.noVaultTags": "\u672A\u5728\u77E5\u8BC6\u5E93\u4E2D\u68C0\u6D4B\u5230\u5DF2\u6709\u6807\u7B7E\u3002",
    "notice.vaultTagsSynced": "\u{1F3F7}\uFE0F \u6807\u7B7E\u5E93\u68C0\u6D4B\u5B8C\u6210\uFF01\u5171\u626B\u63CF\u5230 {total} \u4E2A\u5DF2\u6709\u6807\u7B7E\uFF0C\u81EA\u52A8\u65B0\u53D1\u73B0\u5E76\u540C\u6B65 {added} \u4E2A\u65B0\u6807\u7B7E\u81F3\u89C4\u5219\u5E93\uFF01",
    "notice.batchComplete": "\u6279\u91CF\u6253\u6807\u5B8C\u6210\uFF01\u626B\u63CF {scanned} \u7BC7\u7B14\u8BB0\uFF0C\u4E3A {modified} \u7BC7\u7B14\u8BB0\u8FFD\u52A0\u4E86 {added} \u4E2A\u65B0\u6807\u7B7E\u3002",
    "notice.predictFailed": "Smart Tagger \u9884\u6D4B\u51FA\u9519: {error}",
    "command.suggestTags": "\u4E3A\u5F53\u524D\u6D3B\u52A8\u7B14\u8BB0\u63A8\u8350\u6807\u7B7E (Suggest Tags for Active Note)",
    "command.autoApply": "\u4E00\u952E\u81EA\u52A8\u5E94\u7528\u9AD8\u7F6E\u4FE1\u6807\u7B7E\u5230\u5F53\u524D\u7B14\u8BB0 (Auto-apply Tags to Active Note)",
    "command.batchTagAll": "\u6279\u91CF\u626B\u63CF\u7B14\u8BB0\u5E76\u6DFB\u52A0\u9AD8\u7F6E\u4FE1\u6807\u7B7E (Batch Tag Notes)",
    "command.syncVaultTags": "\u81EA\u52A8\u68C0\u6D4B\u5E76\u540C\u6B65\u77E5\u8BC6\u5E93\u6807\u7B7E\u5E93 (Detect and Sync Vault Tags)",
    "menu.suggestTags": "Smart Tagger: \u667A\u80FD\u6807\u7B7E\u63A8\u8350",
    "settings.title": "Smart Tagger \u8BBE\u7F6E",
    "settings.subtitle": "\u57FA\u4E8E TypeSafe Jev System-1 \u51B3\u7B56\u5F15\u64CE\u7684\u6BEB\u79D2\u7EA7\u667A\u80FD\u7B14\u8BB0\u6807\u7B7E\u63A8\u8350\u4E0E\u5168\u81EA\u52A8\u5206\u7C7B\u52A9\u624B\u3002",
    "settings.section.general": "\u2699\uFE0F \u57FA\u672C\u914D\u7F6E",
    "settings.language.name": "\u754C\u9762\u8BED\u8A00",
    "settings.language.desc": "\u9009\u62E9\u63D2\u4EF6\u754C\u9762\u6240\u4F7F\u7528\u7684\u8BED\u8A00\uFF08\u652F\u6301\u7B80\u4F53\u4E2D\u6587\u4E0E English\uFF09\u3002",
    "settings.apiKey.name": "Jev API \u5BC6\u94A5",
    "settings.apiKey.desc": "TypeSafe Jev \u5B98\u65B9 API \u5BC6\u94A5\uFF0C\u8F93\u5165\u540E\u81EA\u52A8\u91C7\u7528\u5BC6\u7801\u63A9\u7801\u4FDD\u62A4\u3002",
    "settings.apiKey.toggleTooltip": "\u5207\u6362\u663E\u793A/\u9690\u85CF API Key",
    "settings.threshold.name": "\u7F6E\u4FE1\u5EA6\u63A8\u8350\u9608\u503C",
    "settings.threshold.desc": "\u4EC5\u5F53\u6A21\u578B\u6253\u6807\u7F6E\u4FE1\u5EA6\u8FBE\u5230\u6216\u8D85\u8FC7\u8BE5\u9608\u503C\u65F6\u624D\u8FDB\u884C\u63A8\u8350\u6216\u5199\u5165\uFF08\u9ED8\u8BA4 70%\uFF09\u3002",
    "settings.section.actions": "\u{1F680} \u6279\u91CF\u64CD\u4F5C\u4E0E\u7EF4\u62A4",
    "settings.batch.name": "\u6279\u91CF\u626B\u63CF\u6253\u6807",
    "settings.batch.desc": "\u6253\u5F00\u5168\u5E93\u6279\u91CF\u6253\u6807\u9762\u677F\uFF0C\u652F\u6301\u5168\u5E93\u6216\u6309\u6587\u4EF6\u5939\u626B\u63CF\u5E76\u81EA\u52A8\u8FFD\u52A0\u9AD8\u7F6E\u4FE1\u6807\u7B7E\u3002",
    "settings.batch.button": "\u6253\u5F00\u6279\u91CF\u9762\u677F",
    "settings.sync.name": "\u626B\u63CF\u540C\u6B65\u6807\u7B7E\u5E93",
    "settings.sync.desc": "\u5FEB\u901F\u63D0\u53D6\u77E5\u8BC6\u5E93\u5F53\u524D\u6240\u6709\u5DF2\u5B58\u5728\u7684\u5386\u53F2\u6807\u7B7E\uFF0C\u81EA\u52A8\u6269\u5145\u81F3\u4E0B\u65B9\u89C4\u5219\u5E93\u4E2D\u3002",
    "settings.sync.button": "\u626B\u63CF\u6807\u7B7E\u5E93",
    "settings.section.tags": "\u{1F3F7}\uFE0F \u6807\u7B7E\u89C4\u5219\u5E93",
    "settings.tagLibrary.desc": "\u5F53\u524D\u7BA1\u7406\u7684\u5206\u7C7B\u6807\u7B7E\u5217\u8868\u3002\u70B9\u51FB\u5F00\u5173\u53EF\u968F\u65F6\u542F\u7528\u6216\u5173\u95ED\u7279\u5B9A\u6807\u7B7E\u7684\u81EA\u52A8\u8BC4\u4F30\u3002",
    "settings.tagLibrary.tagName": "#{name}",
    "settings.tagLibrary.stats": "\u5171 {total} \u4E2A\u6807\u7B7E\uFF0C\u5DF2\u542F\u7528 {enabled} \u4E2A",
    "settings.tagLibrary.enableAll": "\u5168\u90E8\u542F\u7528",
    "settings.tagLibrary.disableAll": "\u5168\u90E8\u7981\u7528",
    "settings.tagLibrary.empty": "\u{1F4A1} \u89C4\u5219\u5E93\u6682\u65E0\u6807\u7B7E\u3002\u8BF7\u70B9\u51FB\u4E0A\u65B9\u7684\u300C\u626B\u63CF\u6807\u7B7E\u5E93\u300D\u6309\u94AE\uFF0C\u5373\u53EF\u5FEB\u901F\u63D0\u53D6\u77E5\u8BC6\u5E93\u5DF2\u6709\u6807\u7B7E\uFF01",
    "tagSuggest.title": "\u{1F3F7}\uFE0F Smart Tagger: {name}",
    "tagSuggest.loadingSubtitle": "\u6B63\u5728\u5411 Jev System-1 \u51B3\u7B56\u6A21\u578B\u83B7\u53D6\u6BEB\u79D2\u7EA7\u6807\u7B7E\u7F6E\u4FE1\u5EA6\u5206\u6790...",
    "tagSuggest.loading": "AI \u51B3\u7B56\u5206\u6790\u4E2D...",
    "tagSuggest.analysisFailed": "\u274C \u5206\u6790\u5931\u8D25: {error}",
    "tagSuggest.resultSubtitle": "\u63A8\u8350\u7F6E\u4FE1\u5EA6\u9608\u503C \u2265 {threshold}%\u3002\u70B9\u51FB\u6309\u94AE\u5373\u53EF\u5B89\u5168\u5199\u5165\u7B14\u8BB0 Frontmatter\u3002",
    "tagSuggest.empty": "\u672A\u68C0\u6D4B\u5230\u7B26\u5408\u5F53\u524D\u7F6E\u4FE1\u5EA6\u9608\u503C\u7684\u6807\u7B7E\u3002",
    "tagSuggest.alreadyTagged": "(\u5DF2\u6253\u6807)",
    "tagSuggest.addButton": "+ \u6DFB\u52A0",
    "tagSuggest.applyAllButton": "\u26A1 \u4E00\u952E\u5E94\u7528\u6240\u6709\u9AD8\u7F6E\u4FE1\u6807\u7B7E ({count}\u4E2A)",
    "tagSuggest.close": "\u5173\u95ED",
    "batch.title": "\u26A1 Smart Tagger: \u6279\u91CF\u626B\u63CF\u4E0E\u6253\u6807",
    "batch.subtitle": "\u626B\u63CF\u6240\u9009\u6587\u4EF6\u5939\u6216\u6574\u4E2A\u77E5\u8BC6\u5E93\uFF0C\u5E76\u7531 Jev \u6A21\u578B\u8BC4\u4F30\u7B14\u8BB0\u3002\u8FBE\u5230 {threshold}% \u7F6E\u4FE1\u5EA6\u4E14\u5C1A\u672A\u5B58\u5728\u7684\u6807\u7B7E\u4F1A\u5199\u5165 Frontmatter\u3002",
    "batch.scopeLabel": "\u626B\u63CF\u8303\u56F4",
    "batch.scopeDesc": "\u9009\u62E9\u6587\u4EF6\u5939\u540E\uFF0C\u4E5F\u4F1A\u626B\u63CF\u5176\u4E0B\u7EA7\u6587\u4EF6\u5939\u4E2D\u7684 Markdown \u7B14\u8BB0\u3002",
    "batch.scopeAll": "\u6574\u4E2A\u77E5\u8BC6\u5E93",
    "batch.statScanned": "\u5DF2\u626B\u63CF\u7B14\u8BB0",
    "batch.statModified": "\u547D\u4E2D\u6253\u6807\u7B14\u8BB0",
    "batch.statAdded": "\u7D2F\u8BA1\u65B0\u589E\u6807\u7B7E",
    "batch.ready": "\u51C6\u5907\u5C31\u7EEA\uFF0C\u70B9\u51FB\u4E0B\u65B9\u6309\u94AE\u5F00\u59CB\u3002",
    "batch.logHeader": "\u6267\u884C\u65E5\u5FD7:",
    "batch.startHint": "\u70B9\u51FB [\u5F00\u59CB\u6279\u91CF\u6253\u6807] \u5373\u523B\u542F\u52A8\u540E\u53F0\u9AD8\u901F\u8BC4\u4F30...",
    "batch.startButton": "\u{1F680} \u5F00\u59CB\u6279\u91CF\u6253\u6807",
    "batch.close": "\u5173\u95ED",
    "batch.stopButton": "\u23F9\uFE0F \u505C\u6B62\u626B\u63CF",
    "batch.stopping": "\u6B63\u5728\u505C\u6B62...",
    "batch.finishedButton": "\u5B8C\u6210\u5173\u95ED",
    "batch.rescanButton": "\u91CD\u65B0\u626B\u63CF",
    "batch.logStart": "\u5F00\u59CB\u6279\u91CF\u5206\u6790\uFF0C\u8303\u56F4\uFF1A{scope}\uFF0C\u5171 {total} \u7BC7 Markdown \u7B14\u8BB0",
    "batch.logCancelled": "\u7528\u6237\u4E3B\u52A8\u4E2D\u6B62\u4E86\u6279\u91CF\u6253\u6807\u3002",
    "batch.logCurrentFile": "\u6B63\u5728\u5206\u6790 ({index}/{total}): {path}",
    "batch.logAddedTags": "\u2705 [{name}] \u65B0\u589E\u6807\u7B7E: {tags}",
    "batch.logError": "\u274C [{name}] \u9519\u8BEF: {error}",
    "batch.allDone": "\u{1F389} \u6279\u91CF\u6253\u6807\u5168\u90E8\u5B8C\u6210\uFF01"
  },
  en: {
    "plugin.ribbon": "Smart Tagger: Suggest Tags",
    "notice.noActiveFile": "Please open a note in the editor first.",
    "notice.analyzing": "Jev is analyzing note: {name}...",
    "notice.noEligibleTags": "No new tags found at or above the {threshold}% confidence threshold.",
    "notice.autoApplySuccess": "Successfully appended {count} high-confidence tags!",
    "notice.tagsAlreadyExist": "All relevant tags already exist in this note.",
    "notice.autoApplyFailed": "Auto-tagging failed: {error}",
    "notice.tagAdded": "Added tag #{tag}",
    "notice.applyAllSuccess": "Successfully added {count} tags to the frontmatter!",
    "notice.noVaultTags": "No existing tags were detected in this vault.",
    "notice.vaultTagsSynced": "\u{1F3F7}\uFE0F Tag library sync complete! Scanned {total} existing tags and discovered {added} new tags added to the rule library!",
    "notice.batchComplete": "Batch tagging complete! Scanned {scanned} notes and appended {added} new tags across {modified} notes.",
    "notice.predictFailed": "Smart Tagger prediction failed: {error}",
    "command.suggestTags": "Suggest tags for the active note",
    "command.autoApply": "Auto-apply tags to the active note",
    "command.batchTagAll": "Batch scan notes and add high-confidence tags",
    "command.syncVaultTags": "Detect and sync vault tags",
    "menu.suggestTags": "Smart Tagger: Suggest Tags",
    "settings.title": "Smart Tagger Settings",
    "settings.subtitle": "Millisecond System-1 intelligent tag suggestions and automated categorization powered by TypeSafe Jev.",
    "settings.section.general": "\u2699\uFE0F General Settings",
    "settings.language.name": "Interface Language",
    "settings.language.desc": "Choose the display language for the plugin interface.",
    "settings.apiKey.name": "Jev API Key",
    "settings.apiKey.desc": "Your official TypeSafe Jev API key, automatically masked as password dots after entry.",
    "settings.apiKey.toggleTooltip": "Toggle API Key visibility",
    "settings.threshold.name": "Confidence Threshold",
    "settings.threshold.desc": "Only suggest or apply tags when the confidence reaches or exceeds this threshold (Default: 70%).",
    "settings.section.actions": "\u{1F680} Batch Actions & Maintenance",
    "settings.batch.name": "Batch Scan & Tag",
    "settings.batch.desc": "Open the batch tagging panel to scan the entire vault or specific folders.",
    "settings.batch.button": "Open Batch Panel",
    "settings.sync.name": "Sync Vault Tags",
    "settings.sync.desc": "Scan all existing tags across your vault and automatically add new tags to the rule library below.",
    "settings.sync.button": "Scan Vault Tags",
    "settings.section.tags": "\u{1F3F7}\uFE0F Tag Criteria Library",
    "settings.tagLibrary.desc": "Target tags for evaluation. Toggle individual tags on or off as needed.",
    "settings.tagLibrary.tagName": "#{name}",
    "settings.tagLibrary.stats": "{total} tags total, {enabled} enabled",
    "settings.tagLibrary.enableAll": "Enable All",
    "settings.tagLibrary.disableAll": "Disable All",
    "settings.tagLibrary.empty": '\u{1F4A1} No tags in the rule library yet. Click "Scan Vault Tags" above to auto-detect existing tags from your vault!',
    "tagSuggest.title": "\u{1F3F7}\uFE0F Smart Tagger: {name}",
    "tagSuggest.loadingSubtitle": "Requesting millisecond tag confidence analysis from the Jev System-1 decision model...",
    "tagSuggest.loading": "Running AI decision analysis...",
    "tagSuggest.analysisFailed": "\u274C Analysis failed: {error}",
    "tagSuggest.resultSubtitle": "Confidence threshold \u2265 {threshold}%. Click a button to safely write the tag into the note frontmatter.",
    "tagSuggest.empty": "No tags matched the current confidence threshold.",
    "tagSuggest.alreadyTagged": "(already tagged)",
    "tagSuggest.addButton": "+ Add",
    "tagSuggest.applyAllButton": "\u26A1 Apply all high-confidence tags ({count})",
    "tagSuggest.close": "Close",
    "batch.title": "\u26A1 Smart Tagger: Batch scan & tag",
    "batch.subtitle": "Scan the selected folder or the whole vault with the Jev model. Tags at or above the {threshold}% confidence threshold that are not already present will be added to the frontmatter.",
    "batch.scopeLabel": "Scan scope",
    "batch.scopeDesc": "Selecting a folder also includes Markdown notes in its subfolders.",
    "batch.scopeAll": "Entire vault",
    "batch.statScanned": "Notes scanned",
    "batch.statModified": "Notes tagged",
    "batch.statAdded": "Tags added",
    "batch.ready": "Ready. Click the button below to start.",
    "batch.logHeader": "Log:",
    "batch.startHint": "Click [Start batch tagging] to begin high-speed evaluation in the background...",
    "batch.startButton": "\u{1F680} Start batch tagging",
    "batch.close": "Close",
    "batch.stopButton": "\u23F9\uFE0F Stop scan",
    "batch.stopping": "Stopping...",
    "batch.finishedButton": "Done",
    "batch.rescanButton": "Rescan",
    "batch.logStart": "Starting batch analysis in {scope} over {total} Markdown notes",
    "batch.logCancelled": "Batch tagging was cancelled by the user.",
    "batch.logCurrentFile": "Analyzing ({index}/{total}): {path}",
    "batch.logAddedTags": "\u2705 [{name}] added tags: {tags}",
    "batch.logError": "\u274C [{name}] error: {error}",
    "batch.allDone": "\u{1F389} Batch tagging complete!"
  }
};
function t(language, key, params) {
  const template = translations[language]?.[key] ?? translations.en[key] ?? key;
  if (!params) return template;
  return template.replace(
    /\{(\w+)\}/g,
    (match, name) => Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : match
  );
}

// src/batchTagModal.ts
var BatchTagModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.isRunning = false;
    this.isCancelled = false;
    this.selectedFolderPath = "";
    // Metrics
    this.totalFiles = 0;
    this.processedCount = 0;
    this.modifiedFilesCount = 0;
    this.addedTagsCount = 0;
    this.plugin = plugin;
  }
  tr(key, params) {
    return t(this.plugin.settings.language, key, params);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("jev-batch-modal");
    const header = contentEl.createDiv({ cls: "jev-tagger-header" });
    header.createEl("h3", { text: this.tr("batch.title") });
    const thresholdPct = Math.round(this.plugin.settings.confidenceThreshold * 100);
    header.createEl("div", {
      cls: "jev-tagger-subtitle",
      text: this.tr("batch.subtitle", { threshold: thresholdPct })
    });
    const folderPaths = this.app.vault.getAllLoadedFiles().filter((file) => file instanceof import_obsidian2.TFolder && file.path.length > 0).map((folder) => folder.path).sort((a, b) => a.localeCompare(b));
    if (this.selectedFolderPath && !folderPaths.includes(this.selectedFolderPath)) {
      this.selectedFolderPath = "";
    }
    new import_obsidian2.Setting(contentEl).setName(this.tr("batch.scopeLabel")).setDesc(this.tr("batch.scopeDesc")).addDropdown((dropdown) => {
      dropdown.addOption("", this.tr("batch.scopeAll"));
      folderPaths.forEach((path) => dropdown.addOption(path, path));
      dropdown.setValue(this.selectedFolderPath).onChange((path) => {
        this.selectedFolderPath = path;
      });
      this.scopeSelectEl = dropdown.selectEl;
    });
    const statsContainer = contentEl.createDiv({ cls: "jev-batch-stats" });
    const stat1 = statsContainer.createDiv({ cls: "jev-stat-card" });
    this.processedStatEl = stat1.createDiv({ cls: "jev-stat-num", text: "0 / 0" });
    stat1.createDiv({ cls: "jev-stat-label", text: this.tr("batch.statScanned") });
    const stat2 = statsContainer.createDiv({ cls: "jev-stat-card" });
    this.modifiedStatEl = stat2.createDiv({ cls: "jev-stat-num", text: "0" });
    stat2.createDiv({ cls: "jev-stat-label", text: this.tr("batch.statModified") });
    const stat3 = statsContainer.createDiv({ cls: "jev-stat-card" });
    this.addedTagsStatEl = stat3.createDiv({ cls: "jev-stat-num", text: "0" });
    stat3.createDiv({ cls: "jev-stat-label", text: this.tr("batch.statAdded") });
    this.currentFileEl = contentEl.createDiv({
      cls: "jev-batch-current-file",
      text: this.tr("batch.ready")
    });
    const progressContainer = contentEl.createDiv({ cls: "jev-progress-bar-container" });
    this.progressFillEl = progressContainer.createDiv({ cls: "jev-progress-bar-fill" });
    this.progressFillEl.style.width = "0%";
    contentEl.createEl("div", {
      text: this.tr("batch.logHeader"),
      cls: "setting-item-description",
      attr: { style: "margin: 12px 0 4px 0;" }
    });
    this.logContainerEl = contentEl.createDiv({ cls: "jev-batch-log" });
    this.addLog(this.tr("batch.startHint"), "jev-log-skip");
    const footer = contentEl.createDiv({ cls: "jev-actions-footer" });
    this.startBtn = footer.createEl("button", {
      cls: "mod-cta",
      text: this.tr("batch.startButton")
    });
    this.startBtn.onclick = () => this.startBatchProcess();
    this.cancelBtn = footer.createEl("button", { text: this.tr("batch.close") });
    this.cancelBtn.onclick = () => {
      if (this.isRunning) {
        this.isCancelled = true;
        this.cancelBtn.setText(this.tr("batch.stopping"));
        this.cancelBtn.disabled = true;
      } else {
        this.close();
      }
    };
  }
  addLog(text, cls = "jev-log-skip") {
    const item = this.logContainerEl.createDiv({ cls: `jev-log-item ${cls}`, text });
    this.logContainerEl.scrollTop = this.logContainerEl.scrollHeight;
  }
  async startBatchProcess() {
    if (this.isRunning) return;
    const selectedFolderPath = this.selectedFolderPath;
    const files = this.app.vault.getMarkdownFiles().filter((f) => {
      const p = f.path;
      if (selectedFolderPath && !p.startsWith(`${selectedFolderPath}/`)) return false;
      if (p.startsWith(".") || p.includes("/.") || p.includes("\\.")) return false;
      if (p.toLowerCase().includes("templates") || p.toLowerCase().includes("\u6A21\u677F")) return false;
      return true;
    });
    this.totalFiles = files.length;
    this.processedCount = 0;
    this.modifiedFilesCount = 0;
    this.addedTagsCount = 0;
    this.isRunning = true;
    this.isCancelled = false;
    this.startBtn.disabled = true;
    this.scopeSelectEl.disabled = true;
    this.cancelBtn.setText(this.tr("batch.stopButton"));
    this.addLog(
      this.tr("batch.logStart", {
        scope: selectedFolderPath || this.tr("batch.scopeAll"),
        total: this.totalFiles
      }),
      "jev-log-skip"
    );
    for (let idx = 0; idx < files.length; idx++) {
      if (this.isCancelled) {
        this.addLog(this.tr("batch.logCancelled"), "jev-log-skip");
        break;
      }
      const file = files[idx];
      this.currentFileEl.setText(
        this.tr("batch.logCurrentFile", { index: idx + 1, total: this.totalFiles, path: file.path })
      );
      const pct = Math.round((idx + 1) / this.totalFiles * 100);
      this.progressFillEl.style.width = `${pct}%`;
      try {
        const results = await this.plugin.evaluateFile(file);
        const eligible = results.filter((r) => r.probability >= this.plugin.settings.confidenceThreshold);
        const cache = this.app.metadataCache.getFileCache(file);
        const existingTags = /* @__PURE__ */ new Set();
        if (cache?.frontmatter?.tags) {
          const raw = cache.frontmatter.tags;
          if (Array.isArray(raw)) raw.forEach((t2) => existingTags.add(String(t2).replace(/^#/, "")));
          else if (typeof raw === "string") raw.split(/[\s,]+/).forEach((t2) => existingTags.add(t2.replace(/^#/, "")));
        }
        const toAdd = eligible.filter((r) => !existingTags.has(r.tagName));
        if (toAdd.length > 0) {
          let fileModified = false;
          for (const item of toAdd) {
            const added = await this.plugin.addTagToFile(file, item.tagName);
            if (added) {
              this.addedTagsCount++;
              fileModified = true;
            }
          }
          if (fileModified) {
            this.modifiedFilesCount++;
            const tagNames = toAdd.map((t2) => `#${t2.tagName}`).join(", ");
            this.addLog(this.tr("batch.logAddedTags", { name: file.basename, tags: tagNames }), "jev-log-success");
          }
        } else {
        }
      } catch (err) {
        this.addLog(this.tr("batch.logError", { name: file.basename, error: err.message || err }), "jev-log-skip");
      }
      this.processedCount = idx + 1;
      this.processedStatEl.setText(`${this.processedCount} / ${this.totalFiles}`);
      this.modifiedStatEl.setText(`${this.modifiedFilesCount}`);
      this.addedTagsStatEl.setText(`${this.addedTagsCount}`);
      await new Promise((res) => setTimeout(res, 80));
    }
    this.isRunning = false;
    this.currentFileEl.setText(this.tr("batch.allDone"));
    this.progressFillEl.style.width = "100%";
    this.cancelBtn.setText(this.tr("batch.finishedButton"));
    this.cancelBtn.disabled = false;
    this.startBtn.setText(this.tr("batch.rescanButton"));
    this.startBtn.disabled = false;
    this.scopeSelectEl.disabled = false;
    new import_obsidian2.Notice(
      this.tr("notice.batchComplete", {
        scanned: this.processedCount,
        modified: this.modifiedFilesCount,
        added: this.addedTagsCount
      })
    );
  }
  onClose() {
    this.isCancelled = true;
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  endpoint: "https://api.typesafe.ai/v1/systemone",
  language: "zh",
  confidenceThreshold: 0.7,
  tags: []
};
var JevTaggerSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("jev-settings-container");
    const lang = this.plugin.settings.language;
    const headerEl = containerEl.createDiv({ cls: "jev-settings-header" });
    headerEl.createEl("h2", { text: t(lang, "settings.title") });
    headerEl.createEl("p", {
      text: t(lang, "settings.subtitle"),
      cls: "setting-item-description"
    });
    new import_obsidian3.Setting(containerEl).setHeading().setName(t(lang, "settings.section.general"));
    new import_obsidian3.Setting(containerEl).setName(t(lang, "settings.language.name")).setDesc(t(lang, "settings.language.desc")).addDropdown((dropdown) => {
      LANGUAGES.forEach((key) => {
        dropdown.addOption(key, LANGUAGE_OPTIONS[key]);
      });
      dropdown.setValue(lang).onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    let keyInputEl;
    let isRevealed = false;
    new import_obsidian3.Setting(containerEl).setName(t(lang, "settings.apiKey.name")).setDesc(t(lang, "settings.apiKey.desc")).addText((text) => {
      keyInputEl = text.inputEl;
      keyInputEl.type = "password";
      keyInputEl.placeholder = "apikey_...";
      keyInputEl.addClass("jev-settings-apikey-input");
      text.setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("eye-off").setTooltip(t(lang, "settings.apiKey.toggleTooltip")).onClick(() => {
        isRevealed = !isRevealed;
        keyInputEl.type = isRevealed ? "text" : "password";
        btn.setIcon(isRevealed ? "eye" : "eye-off");
      });
    });
    const thresholdSetting = new import_obsidian3.Setting(containerEl).setName(t(lang, "settings.threshold.name")).setDesc(t(lang, "settings.threshold.desc"));
    const currentPct = Math.round(this.plugin.settings.confidenceThreshold * 100);
    const badgeEl = thresholdSetting.controlEl.createSpan({
      cls: "jev-threshold-badge",
      text: `${currentPct}%`
    });
    thresholdSetting.addSlider(
      (slider) => slider.setLimits(0.1, 0.95, 0.05).setValue(this.plugin.settings.confidenceThreshold).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.confidenceThreshold = value;
        badgeEl.setText(`${Math.round(value * 100)}%`);
        await this.plugin.saveSettings();
      })
    );
    thresholdSetting.controlEl.prepend(badgeEl);
    new import_obsidian3.Setting(containerEl).setHeading().setName(t(lang, "settings.section.actions"));
    new import_obsidian3.Setting(containerEl).setName(t(lang, "settings.batch.name")).setDesc(t(lang, "settings.batch.desc")).addButton(
      (btn) => btn.setButtonText(t(lang, "settings.batch.button")).setCta().onClick(() => {
        new BatchTagModal(this.app, this.plugin).open();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(t(lang, "settings.sync.name")).setDesc(t(lang, "settings.sync.desc")).addButton(
      (btn) => btn.setButtonText(t(lang, "settings.sync.button")).onClick(async () => {
        await this.plugin.detectAndSyncVaultTags();
        this.display();
      })
    );
    new import_obsidian3.Setting(containerEl).setHeading().setName(t(lang, "settings.section.tags")).setDesc(t(lang, "settings.tagLibrary.desc"));
    const tags = this.plugin.settings.tags;
    const totalTags = tags.length;
    if (totalTags > 0) {
      const enabledCount = tags.filter((tag) => tag.enabled).length;
      const toolbar = containerEl.createDiv({ cls: "jev-tag-toolbar" });
      const statsEl = toolbar.createDiv({
        cls: "jev-tag-stats",
        text: t(lang, "settings.tagLibrary.stats", { total: totalTags, enabled: enabledCount })
      });
      const toolbarButtons = toolbar.createDiv({ cls: "jev-tag-toolbar-buttons" });
      const enableAllBtn = toolbarButtons.createEl("button", {
        cls: "jev-tag-action-btn",
        text: t(lang, "settings.tagLibrary.enableAll")
      });
      enableAllBtn.onclick = async () => {
        tags.forEach((tag) => tag.enabled = true);
        await this.plugin.saveSettings();
        this.display();
      };
      const disableAllBtn = toolbarButtons.createEl("button", {
        cls: "jev-tag-action-btn",
        text: t(lang, "settings.tagLibrary.disableAll")
      });
      disableAllBtn.onclick = async () => {
        tags.forEach((tag) => tag.enabled = false);
        await this.plugin.saveSettings();
        this.display();
      };
      const tagGrid = containerEl.createDiv({ cls: "jev-tag-library-grid" });
      tags.forEach((tag, index) => {
        const tagCard = tagGrid.createDiv({
          cls: `jev-tag-card ${tag.enabled ? "is-enabled" : "is-disabled"}`
        });
        const chip = tagCard.createDiv({ cls: "jev-tag-card-chip" });
        chip.createSpan({ cls: "jev-tag-hash", text: "#" });
        const nameEl = chip.createSpan({ cls: "jev-tag-name", text: tag.name });
        if (tag.instructions) {
          nameEl.title = tag.instructions;
        }
        const toggleContainer = tagCard.createDiv({ cls: "jev-tag-card-toggle" });
        new import_obsidian3.Setting(toggleContainer).addToggle((toggle) => {
          toggle.setValue(tag.enabled).onChange(async (val) => {
            tags[index].enabled = val;
            tagCard.toggleClass("is-enabled", val);
            tagCard.toggleClass("is-disabled", !val);
            await this.plugin.saveSettings();
            const updatedEnabled = tags.filter((item) => item.enabled).length;
            statsEl.setText(
              t(lang, "settings.tagLibrary.stats", { total: totalTags, enabled: updatedEnabled })
            );
          });
        });
      });
    } else {
      const emptyEl = containerEl.createDiv({ cls: "jev-tag-empty-state" });
      emptyEl.createEl("div", {
        cls: "jev-tag-empty-text",
        text: t(lang, "settings.tagLibrary.empty")
      });
    }
  }
};

// src/tagSuggestModal.ts
var import_obsidian4 = require("obsidian");
var TagSuggestModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, file) {
    super(app);
    this.plugin = plugin;
    this.file = file;
    this.results = [];
    this.existingTags = /* @__PURE__ */ new Set();
    this.isLoading = true;
  }
  tr(key, params) {
    return t(this.plugin.settings.language, key, params);
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("jev-tagger-modal");
    const header = contentEl.createDiv({ cls: "jev-tagger-header" });
    header.createEl("h3", { text: this.tr("tagSuggest.title", { name: this.file.basename }) });
    header.createEl("div", {
      cls: "jev-tagger-subtitle",
      text: this.tr("tagSuggest.loadingSubtitle")
    });
    const loadingEl = contentEl.createDiv({ cls: "jev-loading-container" });
    loadingEl.createDiv({ cls: "jev-spinner" });
    loadingEl.createEl("span", { text: this.tr("tagSuggest.loading") });
    await this.readExistingTags();
    try {
      this.results = await this.plugin.evaluateFile(this.file);
      this.isLoading = false;
      this.renderResults();
    } catch (error) {
      loadingEl.empty();
      loadingEl.createEl("div", {
        cls: "setting-item-description",
        text: this.tr("tagSuggest.analysisFailed", { error: error.message || error })
      });
      new import_obsidian4.Notice(this.tr("notice.predictFailed", { error: error.message || error }));
    }
  }
  async readExistingTags() {
    const cache = this.app.metadataCache.getFileCache(this.file);
    if (cache?.frontmatter?.tags) {
      const raw = cache.frontmatter.tags;
      if (Array.isArray(raw)) {
        raw.forEach((t2) => this.existingTags.add(String(t2).replace(/^#/, "")));
      } else if (typeof raw === "string") {
        raw.split(/[\s,]+/).forEach((t2) => this.existingTags.add(t2.replace(/^#/, "")));
      }
    }
  }
  renderResults() {
    const { contentEl } = this;
    contentEl.empty();
    const header = contentEl.createDiv({ cls: "jev-tagger-header" });
    header.createEl("h3", { text: this.tr("tagSuggest.title", { name: this.file.basename }) });
    const thresholdPct = Math.round(this.plugin.settings.confidenceThreshold * 100);
    header.createEl("div", {
      cls: "jev-tagger-subtitle",
      text: this.tr("tagSuggest.resultSubtitle", { threshold: thresholdPct })
    });
    const tagList = contentEl.createDiv({ cls: "jev-tag-list" });
    if (this.results.length === 0) {
      tagList.createDiv({
        cls: "setting-item-description",
        text: this.tr("tagSuggest.empty")
      });
    } else {
      this.results.forEach((res) => {
        const isExisting = this.existingTags.has(res.tagName);
        const isHighConf = res.probability >= this.plugin.settings.confidenceThreshold;
        const item = tagList.createDiv({ cls: "jev-tag-item" });
        const info = item.createDiv({ cls: "jev-tag-info" });
        const nameRow = info.createDiv({ cls: "jev-tag-name-row" });
        nameRow.createEl("span", { cls: "jev-tag-badge", text: `#${res.tagName}` });
        if (isExisting) {
          nameRow.createEl("span", { cls: "jev-tag-existing", text: this.tr("tagSuggest.alreadyTagged") });
        }
        info.createEl("div", { cls: "jev-tag-desc", text: res.description });
        const progressContainer = info.createDiv({ cls: "jev-progress-bar-container" });
        const pct = Math.round(res.probability * 100);
        const fill = progressContainer.createDiv({ cls: "jev-progress-bar-fill" });
        fill.style.width = `${pct}%`;
        if (pct >= 80) fill.style.backgroundColor = "var(--color-green, #10b981)";
        else if (pct >= 60) fill.style.backgroundColor = "var(--color-blue, #3b82f6)";
        else fill.style.backgroundColor = "var(--color-yellow, #f59e0b)";
        const right = item.createDiv({ cls: "jev-tag-actions", attr: { style: "display: flex; align-items: center; gap: 10px;" } });
        right.createEl("span", { cls: "jev-confidence-score", text: `${pct}%` });
        if (!isExisting) {
          const addBtn = right.createEl("button", {
            cls: "mod-cta jev-btn-add",
            text: this.tr("tagSuggest.addButton")
          });
          addBtn.onclick = async () => {
            await this.addTagToNote(res.tagName);
            this.existingTags.add(res.tagName);
            this.renderResults();
          };
        }
      });
    }
    const footer = contentEl.createDiv({ cls: "jev-actions-footer" });
    const highConfNewTags = this.results.filter((r) => r.probability >= this.plugin.settings.confidenceThreshold && !this.existingTags.has(r.tagName)).map((r) => r.tagName);
    if (highConfNewTags.length > 0) {
      const applyAllBtn = footer.createEl("button", {
        cls: "mod-cta",
        text: this.tr("tagSuggest.applyAllButton", { count: highConfNewTags.length })
      });
      applyAllBtn.onclick = async () => {
        for (const tag of highConfNewTags) {
          await this.addTagToNote(tag);
          this.existingTags.add(tag);
        }
        new import_obsidian4.Notice(this.tr("notice.applyAllSuccess", { count: highConfNewTags.length }));
        this.close();
      };
    }
    const closeBtn = footer.createEl("button", { text: this.tr("tagSuggest.close") });
    closeBtn.onclick = () => this.close();
  }
  async addTagToNote(tagName) {
    await this.plugin.addTagToFile(this.file, tagName);
    new import_obsidian4.Notice(this.tr("notice.tagAdded", { tag: tagName }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var LEGACY_DEFAULT_TAG_RULES = [
  {
    name: "\u5F02\u5E38\u68C0\u6D4B",
    instructions: "Is this note primarily about image anomaly detection or anomaly segmentation?",
    matchCriteria: "Computer vision anomaly detection, defect localization, and benchmark experiments.",
    otherCriteria: "General database schemas, web engineering, reading lists, or thesis checklists."
  },
  {
    name: "\u793E\u4EA4\u5A92\u4F53",
    instructions: "Is this note primarily about social media, creator accounts, or tweets?",
    matchCriteria: "Social platforms, creator profiles, tweet drafts, or audience growth.",
    otherCriteria: "Machine learning research, backend coding, or internal project planning."
  },
  {
    name: "\u8D44\u8BAF",
    instructions: "Does this note primarily record recent news, announcements, or industry developments?",
    matchCriteria: "The note reports or aggregates external news, model releases, company updates, or daily roundups.",
    otherCriteria: "An evergreen tutorial, research explanation, personal plan, or general design document."
  },
  {
    name: "AI",
    instructions: "Is this note primarily about artificial intelligence models, AI agents, or AI tools?",
    matchCriteria: "Artificial intelligence models, AI agents, LLM prompting, or AI tools.",
    otherCriteria: "General software development, database administration, UI styling, or personal notes."
  }
];
var JevTaggerPlugin = class extends import_obsidian5.Plugin {
  tr(key, params) {
    return t(this.settings.language, key, params);
  }
  async onload() {
    await this.loadSettings();
    this.jevClient = new JevClient(this.settings.apiKey, this.settings.endpoint);
    this.addRibbonIcon("tags", this.tr("plugin.ribbon"), (evt) => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        new TagSuggestModal(this.app, this, activeFile).open();
      } else {
        new import_obsidian5.Notice(this.tr("notice.noActiveFile"));
      }
    });
    this.addCommand({
      id: "jev-suggest-tags",
      name: this.tr("command.suggestTags"),
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            new TagSuggestModal(this.app, this, activeFile).open();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "jev-auto-apply-tags",
      name: this.tr("command.autoApply"),
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            this.autoApplyTags(activeFile);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "jev-batch-tag-all",
      name: this.tr("command.batchTagAll"),
      callback: () => {
        new BatchTagModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "jev-sync-vault-tags",
      name: this.tr("command.syncVaultTags"),
      callback: async () => {
        await this.detectAndSyncVaultTags();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle(this.tr("menu.suggestTags")).setIcon("tags").onClick(() => {
              new TagSuggestModal(this.app, this, file).open();
            });
          });
        }
      })
    );
    this.addSettingTab(new JevTaggerSettingTab(this.app, this));
    console.log("Smart Tagger plugin loaded.");
  }
  onunload() {
    console.log("Smart Tagger plugin unloaded.");
  }
  async loadSettings() {
    const savedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, savedData);
    if (Array.isArray(savedData?.tags)) {
      const filteredTags = this.settings.tags.filter(
        (tag) => !LEGACY_DEFAULT_TAG_RULES.some(
          (rule) => tag.name === rule.name && tag.instructions === rule.instructions && tag.matchCriteria === rule.matchCriteria && tag.otherCriteria === rule.otherCriteria
        )
      );
      if (filteredTags.length !== this.settings.tags.length) {
        this.settings.tags = filteredTags;
        await this.saveData(this.settings);
      }
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.jevClient) {
      this.jevClient.setApiKey(this.settings.apiKey);
    }
  }
  /**
   * Extracts clean state for Jev System-1 model evaluation
   */
  async buildNoteState(file) {
    const rawContent = await this.app.vault.read(file);
    let text = rawContent.replace(/^---[\s\S]*?---\s*/, "");
    text = text.replace(/(^|\s)#[^\s#]+/g, "$1").trim();
    const title = file.basename;
    const introduction = text.slice(0, 450);
    const headings = [];
    const headingMatches = text.match(/^#{1,4}\s+(.+)$/gm);
    if (headingMatches) {
      for (const h of headingMatches.slice(0, 8)) {
        headings.push(h.replace(/^#{1,4}\s+/, "").trim());
      }
    }
    let excerpt = "";
    if (text.length > 700) {
      excerpt = text.slice(-260);
    }
    const state = {
      title,
      headings,
      content_start: introduction,
      content_excerpt: excerpt
    };
    if (text.length < 300) {
      const folder = file.parent ? file.parent.path : "";
      state["folder_context"] = `Folder location: ${folder}`;
    }
    return state;
  }
  /**
   * Calls Jev to evaluate the note against enabled tags
   */
  async evaluateFile(file) {
    const state = await this.buildNoteState(file);
    return await this.jevClient.evaluateNote(state, this.settings.tags);
  }
  /**
   * Auto applies tags that meet the threshold
   */
  async autoApplyTags(file) {
    new import_obsidian5.Notice(this.tr("notice.analyzing", { name: file.basename }));
    try {
      const results = await this.evaluateFile(file);
      const eligible = results.filter((r) => r.probability >= this.settings.confidenceThreshold);
      if (eligible.length === 0) {
        new import_obsidian5.Notice(
          this.tr("notice.noEligibleTags", {
            threshold: Math.round(this.settings.confidenceThreshold * 100)
          })
        );
        return;
      }
      let addedCount = 0;
      for (const res of eligible) {
        const added = await this.addTagToFile(file, res.tagName);
        if (added) addedCount++;
      }
      if (addedCount > 0) {
        new import_obsidian5.Notice(this.tr("notice.autoApplySuccess", { count: addedCount }));
      } else {
        new import_obsidian5.Notice(this.tr("notice.tagsAlreadyExist"));
      }
    } catch (e) {
      new import_obsidian5.Notice(this.tr("notice.autoApplyFailed", { error: e.message || e }));
    }
  }
  /**
   * Safely adds tag to frontmatter using Obsidian's processFrontMatter API
   */
  async addTagToFile(file, newTag) {
    let modified = false;
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      let currentTags = [];
      if (frontmatter.tags) {
        if (Array.isArray(frontmatter.tags)) {
          currentTags = frontmatter.tags.map((t2) => String(t2).replace(/^#/, ""));
        } else if (typeof frontmatter.tags === "string") {
          currentTags = frontmatter.tags.split(/[\s,]+/).map((t2) => t2.replace(/^#/, ""));
        }
      }
      if (!currentTags.includes(newTag)) {
        currentTags.push(newTag);
        modified = true;
      }
      frontmatter.tags = currentTags;
    });
    return modified;
  }
  /**
   * Detects all tags present in the current Obsidian Vault using metadataCache
   * and syncs them into the plugin's tag library.
   */
  async detectAndSyncVaultTags() {
    const allTagsMap = this.app.metadataCache.getTags();
    const tagKeys = Object.keys(allTagsMap);
    if (tagKeys.length === 0) {
      new import_obsidian5.Notice(this.tr("notice.noVaultTags"));
      return { added: 0, total: 0 };
    }
    let addedCount = 0;
    const existingNames = new Set(this.settings.tags.map((t2) => t2.name));
    const sortedTags = tagKeys.map((rawTag) => ({
      name: rawTag.replace(/^#/, "").trim(),
      count: allTagsMap[rawTag]
    })).filter((t2) => t2.name.length > 0 && !t2.name.includes("/")).sort((a, b) => b.count - a.count);
    for (const t2 of sortedTags) {
      if (!existingNames.has(t2.name)) {
        this.settings.tags.push({
          name: t2.name,
          instructions: `Is this note primarily about ${t2.name}?`,
          matchCriteria: `${t2.name} and related topics.`,
          otherCriteria: "Other topics.",
          enabled: true
        });
        existingNames.add(t2.name);
        addedCount++;
      }
    }
    await this.saveSettings();
    new import_obsidian5.Notice(this.tr("notice.vaultTagsSynced", { total: sortedTags.length, added: addedCount }));
    return { added: addedCount, total: sortedTags.length };
  }
};
