/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JevTaggerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/jevClient.ts
var import_obsidian = require("obsidian");
var JevClient = class {
  constructor(apiKey, endpoint = "https://api.typesafe.ai/v1/systemone") {
    this.apiKey = apiKey;
    this.endpoint = endpoint;
  }
  setApiKey(key) {
    this.apiKey = key;
  }
  async evaluateNote(state, tags) {
    if (!this.apiKey) {
      throw new Error("Jev API Key is not configured. Please set it in the plugin settings.");
    }
    const enabledTags = tags.filter((t) => t.enabled);
    if (enabledTags.length === 0) {
      return [];
    }
    const questions = {};
    for (const tag of enabledTags) {
      questions[`q_${tag.name}`] = {
        type: "choice",
        instructions: tag.instructions,
        criteria: {
          match: tag.matchCriteria,
          other: tag.otherCriteria
        }
      };
    }
    const payload = {
      model: "jev-latest",
      state,
      questions
    };
    const response = await (0, import_obsidian.requestUrl)({
      url: this.endpoint,
      method: "POST",
      headers: {
        Authorization: `Bearer ${this.apiKey}`,
        "Content-Type": "application/json",
        "User-Agent": "obsidian-jev-tagger/1.0"
      },
      body: JSON.stringify(payload)
    });
    if (response.status !== 200) {
      throw new Error(`Jev API Error (${response.status}): ${response.text}`);
    }
    const data = response.json;
    const results = [];
    for (const tag of enabledTags) {
      const ans = data.answers[`q_${tag.name}`];
      if (!ans) continue;
      let matchProb = 0;
      if (ans.probabilities && typeof ans.probabilities.match === "number") {
        matchProb = ans.probabilities.match;
      } else if (ans.choice === "match") {
        matchProb = ans.confidence ?? 1;
      } else {
        matchProb = 0;
      }
      results.push({
        tagName: tag.name,
        probability: matchProb,
        confidence: ans.confidence ?? matchProb,
        isMatch: ans.choice === "match",
        description: tag.matchCriteria
      });
    }
    results.sort((a, b) => b.probability - a.probability);
    return results;
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/batchTagModal.ts
var import_obsidian2 = require("obsidian");
var BatchTagModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.isRunning = false;
    this.isCancelled = false;
    // Metrics
    this.totalFiles = 0;
    this.processedCount = 0;
    this.modifiedFilesCount = 0;
    this.addedTagsCount = 0;
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("jev-batch-modal");
    const header = contentEl.createDiv({ cls: "jev-tagger-header" });
    header.createEl("h3", { text: "\u26A1 Smart Tagger: \u5168\u5E93\u6279\u91CF\u626B\u63CF\u6253\u6807" });
    const thresholdPct = Math.round(this.plugin.settings.confidenceThreshold * 100);
    header.createEl("div", {
      cls: "jev-tagger-subtitle",
      text: `\u5C06\u5168\u5E93\u626B\u63CF\u7B14\u8BB0\uFF0C\u901A\u8FC7 Jev System-1 \u6A21\u578B\u9AD8\u901F\u5224\u5B9A\u3002\u82E5\u68C0\u6D4B\u5230\u7F6E\u4FE1\u5EA6 \u2265 ${thresholdPct}% \u7684\u672A\u6DFB\u52A0\u6807\u7B7E\uFF0C\u5C06\u81EA\u52A8\u5B89\u5168\u5199\u5165 Frontmatter\u3002`
    });
    const statsContainer = contentEl.createDiv({ cls: "jev-batch-stats" });
    const stat1 = statsContainer.createDiv({ cls: "jev-stat-card" });
    this.processedStatEl = stat1.createDiv({ cls: "jev-stat-num", text: "0 / 0" });
    stat1.createDiv({ cls: "jev-stat-label", text: "\u5DF2\u626B\u63CF\u7B14\u8BB0" });
    const stat2 = statsContainer.createDiv({ cls: "jev-stat-card" });
    this.modifiedStatEl = stat2.createDiv({ cls: "jev-stat-num", text: "0" });
    stat2.createDiv({ cls: "jev-stat-label", text: "\u547D\u4E2D\u6253\u6807\u7B14\u8BB0" });
    const stat3 = statsContainer.createDiv({ cls: "jev-stat-card" });
    this.addedTagsStatEl = stat3.createDiv({ cls: "jev-stat-num", text: "0" });
    stat3.createDiv({ cls: "jev-stat-label", text: "\u7D2F\u8BA1\u65B0\u589E\u6807\u7B7E" });
    this.currentFileEl = contentEl.createDiv({
      cls: "jev-batch-current-file",
      text: "\u51C6\u5907\u5C31\u7EEA\uFF0C\u70B9\u51FB\u4E0B\u65B9\u6309\u94AE\u5F00\u59CB\u3002"
    });
    const progressContainer = contentEl.createDiv({ cls: "jev-progress-bar-container" });
    this.progressFillEl = progressContainer.createDiv({ cls: "jev-progress-bar-fill" });
    this.progressFillEl.style.width = "0%";
    contentEl.createEl("div", {
      text: "\u6267\u884C\u65E5\u5FD7:",
      cls: "setting-item-description",
      attr: { style: "margin: 12px 0 4px 0;" }
    });
    this.logContainerEl = contentEl.createDiv({ cls: "jev-batch-log" });
    this.addLog("\u70B9\u51FB [\u5F00\u59CB\u6279\u91CF\u6253\u6807] \u5373\u523B\u542F\u52A8\u540E\u53F0\u9AD8\u901F\u8BC4\u4F30...", "jev-log-skip");
    const footer = contentEl.createDiv({ cls: "jev-actions-footer" });
    this.startBtn = footer.createEl("button", {
      cls: "mod-cta",
      text: "\u{1F680} \u5F00\u59CB\u5168\u5E93\u6279\u91CF\u6253\u6807"
    });
    this.startBtn.onclick = () => this.startBatchProcess();
    this.cancelBtn = footer.createEl("button", { text: "\u5173\u95ED" });
    this.cancelBtn.onclick = () => {
      if (this.isRunning) {
        this.isCancelled = true;
        this.cancelBtn.setText("\u6B63\u5728\u505C\u6B62...");
        this.cancelBtn.disabled = true;
      } else {
        this.close();
      }
    };
  }
  addLog(text, cls = "jev-log-skip") {
    const item = this.logContainerEl.createDiv({ cls: `jev-log-item ${cls}`, text });
    this.logContainerEl.scrollTop = this.logContainerEl.scrollHeight;
  }
  async startBatchProcess() {
    if (this.isRunning) return;
    const files = this.app.vault.getMarkdownFiles().filter((f) => {
      const p = f.path;
      if (p.startsWith(".") || p.includes("/.") || p.includes("\\.")) return false;
      if (p.toLowerCase().includes("templates") || p.toLowerCase().includes("\u6A21\u677F")) return false;
      return true;
    });
    this.totalFiles = files.length;
    this.processedCount = 0;
    this.modifiedFilesCount = 0;
    this.addedTagsCount = 0;
    this.isRunning = true;
    this.isCancelled = false;
    this.startBtn.disabled = true;
    this.cancelBtn.setText("\u23F9\uFE0F \u505C\u6B62\u626B\u63CF");
    this.addLog(`\u5F00\u59CB\u5168\u5E93\u6279\u91CF\u5206\u6790\uFF0C\u76EE\u6807 Markdown \u7B14\u8BB0: ${this.totalFiles} \u7BC7`, "jev-log-skip");
    for (let idx = 0; idx < files.length; idx++) {
      if (this.isCancelled) {
        this.addLog("\u7528\u6237\u4E3B\u52A8\u4E2D\u6B62\u4E86\u6279\u91CF\u6253\u6807\u3002", "jev-log-skip");
        break;
      }
      const file = files[idx];
      this.currentFileEl.setText(`\u6B63\u5728\u5206\u6790 (${idx + 1}/${this.totalFiles}): ${file.path}`);
      const pct = Math.round((idx + 1) / this.totalFiles * 100);
      this.progressFillEl.style.width = `${pct}%`;
      try {
        const results = await this.plugin.evaluateFile(file);
        const eligible = results.filter((r) => r.probability >= this.plugin.settings.confidenceThreshold);
        const cache = this.app.metadataCache.getFileCache(file);
        const existingTags = /* @__PURE__ */ new Set();
        if (cache?.frontmatter?.tags) {
          const raw = cache.frontmatter.tags;
          if (Array.isArray(raw)) raw.forEach((t) => existingTags.add(String(t).replace(/^#/, "")));
          else if (typeof raw === "string") raw.split(/[\s,]+/).forEach((t) => existingTags.add(t.replace(/^#/, "")));
        }
        const toAdd = eligible.filter((r) => !existingTags.has(r.tagName));
        if (toAdd.length > 0) {
          let fileModified = false;
          for (const item of toAdd) {
            const added = await this.plugin.addTagToFile(file, item.tagName);
            if (added) {
              this.addedTagsCount++;
              fileModified = true;
            }
          }
          if (fileModified) {
            this.modifiedFilesCount++;
            const tagNames = toAdd.map((t) => `#${t.tagName}`).join(", ");
            this.addLog(`\u2705 [${file.basename}] \u65B0\u589E\u6807\u7B7E: ${tagNames}`, "jev-log-success");
          }
        } else {
        }
      } catch (err) {
        this.addLog(`\u274C [${file.basename}] \u9519\u8BEF: ${err.message || err}`, "jev-log-skip");
      }
      this.processedCount = idx + 1;
      this.processedStatEl.setText(`${this.processedCount} / ${this.totalFiles}`);
      this.modifiedStatEl.setText(`${this.modifiedFilesCount}`);
      this.addedTagsStatEl.setText(`${this.addedTagsCount}`);
      await new Promise((res) => setTimeout(res, 80));
    }
    this.isRunning = false;
    this.currentFileEl.setText("\u{1F389} \u6279\u91CF\u6253\u6807\u5168\u90E8\u5B8C\u6210\uFF01");
    this.progressFillEl.style.width = "100%";
    this.cancelBtn.setText("\u5B8C\u6210\u5173\u95ED");
    this.cancelBtn.disabled = false;
    this.startBtn.setText("\u91CD\u65B0\u626B\u63CF");
    this.startBtn.disabled = false;
    new import_obsidian2.Notice(`\u5168\u5E93\u6253\u6807\u5B8C\u6210\uFF01\u626B\u63CF ${this.processedCount} \u7BC7\u7B14\u8BB0\uFF0C\u4E3A ${this.modifiedFilesCount} \u7BC7\u7B14\u8BB0\u8FFD\u52A0\u4E86 ${this.addedTagsCount} \u4E2A\u65B0\u6807\u7B7E\u3002`);
  }
  onClose() {
    this.isCancelled = true;
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings.ts
var DEFAULT_TAG_DEFINITIONS = [
  {
    name: "\u5F02\u5E38\u68C0\u6D4B",
    instructions: "Is this note primarily about image anomaly detection or anomaly segmentation?",
    matchCriteria: "Computer vision anomaly detection, defect localization, and benchmark experiments.",
    otherCriteria: "General database schemas, web engineering, reading lists, or thesis checklists.",
    enabled: true
  },
  {
    name: "\u793E\u4EA4\u5A92\u4F53",
    instructions: "Is this note primarily about social media, creator accounts, or tweets?",
    matchCriteria: "Social platforms, creator profiles, tweet drafts, or audience growth.",
    otherCriteria: "Machine learning research, backend coding, or internal project planning.",
    enabled: true
  },
  {
    name: "\u8D44\u8BAF",
    instructions: "Does this note primarily record recent news, announcements, or industry developments?",
    matchCriteria: "The note reports or aggregates external news, model releases, company updates, or daily roundups.",
    otherCriteria: "An evergreen tutorial, research explanation, personal plan, or general design document.",
    enabled: true
  },
  {
    name: "AI",
    instructions: "Is this note primarily about artificial intelligence models, AI agents, or AI tools?",
    matchCriteria: "Artificial intelligence models, AI agents, LLM prompting, or AI tools.",
    otherCriteria: "General software development, database administration, UI styling, or personal notes.",
    enabled: true
  }
];
var DEFAULT_SETTINGS = {
  apiKey: "",
  endpoint: "https://api.typesafe.ai/v1/systemone",
  confidenceThreshold: 0.7,
  autoAddParentAiTag: true,
  tags: DEFAULT_TAG_DEFINITIONS
};
var JevTaggerSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smart Tagger \u8BBE\u7F6E" });
    containerEl.createEl("p", {
      text: "\u57FA\u4E8E TypeSafe Jev System-1 \u6A21\u578B\u7684\u6BEB\u79D2\u7EA7\u667A\u80FD\u7B14\u8BB0\u6807\u7B7E\u63A8\u8350\u4E0E\u5168\u81EA\u52A8\u5206\u7C7B\u52A9\u624B\u3002",
      cls: "setting-item-description"
    });
    let keyInputEl;
    let isRevealed = false;
    new import_obsidian3.Setting(containerEl).setName("Jev API Key").setDesc("\u4F60\u7684 TypeSafe Jev \u5B98\u65B9 API \u5BC6\u94A5\uFF08\u8F93\u5165\u540E\u4EE5\u5BC6\u7801\u5BC6\u6587\u906E\u7F69\u4FDD\u62A4\uFF09\u3002").addText((text) => {
      keyInputEl = text.inputEl;
      keyInputEl.type = "password";
      keyInputEl.placeholder = "apikey_...";
      text.setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    }).addExtraButton((btn) => {
      btn.setIcon("eye-off").setTooltip("\u5207\u6362\u663E\u793A/\u9690\u85CF API Key").onClick(() => {
        isRevealed = !isRevealed;
        keyInputEl.type = isRevealed ? "text" : "password";
        btn.setIcon(isRevealed ? "eye" : "eye-off");
      });
    });
    new import_obsidian3.Setting(containerEl).setName("\u7F6E\u4FE1\u5EA6\u63A8\u8350\u9608\u503C").setDesc("\u4EC5\u63A8\u8350\u7F6E\u4FE1\u5EA6\u5927\u4E8E\u7B49\u4E8E\u8BE5\u9608\u503C\u7684\u6807\u7B7E\uFF08\u9ED8\u8BA4 0.70\uFF0C\u5B9E\u6D4B\u5177\u5907 95%~100% \u6781\u9AD8\u51C6\u786E\u5EA6\uFF09\u3002").addSlider(
      (slider) => slider.setLimits(0.1, 0.95, 0.05).setValue(this.plugin.settings.confidenceThreshold).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.confidenceThreshold = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u81EA\u52A8\u7EE7\u627F\u7236\u6807\u7B7E #AI").setDesc("\u5F53\u547D\u4E2D\u3010\u5F02\u5E38\u68C0\u6D4B\u3011\u7B49\u5177\u4F53 AI \u5B50\u9886\u57DF\u6807\u7B7E\u65F6\uFF0C\u81EA\u52A8\u5728 Frontmatter \u8FFD\u52A0\u7236\u6807\u7B7E #AI\u3002").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoAddParentAiTag).onChange(async (value) => {
        this.plugin.settings.autoAddParentAiTag = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u26A1 \u5FEB\u6377\u64CD\u4F5C\u4E0E\u5168\u5E93\u7EF4\u62A4" });
    new import_obsidian3.Setting(containerEl).setName("\u5168\u5E93\u7B14\u8BB0\u6279\u91CF\u626B\u63CF\u4E0E\u6253\u6807").setDesc("\u6253\u5F00\u5168\u5E93\u6279\u91CF\u6253\u6807\u9762\u677F\uFF0C\u81EA\u52A8\u626B\u63CF\u6574\u4E2A\u77E5\u8BC6\u5E93\u5E76\u4E3A\u6240\u6709\u7B14\u8BB0\u6DFB\u52A0\u9AD8\u7F6E\u4FE1\u672A\u6DFB\u52A0\u6807\u7B7E\u3002").addButton(
      (btn) => btn.setButtonText("\u{1F680} \u6253\u5F00\u6279\u91CF\u6253\u6807\u9762\u677F").setCta().onClick(() => {
        new BatchTagModal(this.app, this.plugin).open();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u81EA\u52A8\u68C0\u6D4B\u5E76\u540C\u6B65\u77E5\u8BC6\u5E93\u6807\u7B7E\u5E93").setDesc("\u81EA\u52A8\u626B\u63CF\u77E5\u8BC6\u5E93\u5F53\u524D\u5DF2\u5B58\u5728\u7684\u6240\u6709\u5386\u53F2\u6807\u7B7E\uFF0C\u5E76\u5C06\u65B0\u53D1\u73B0\u7684\u6807\u7B7E\u81EA\u52A8\u8865\u5145\u5230\u4E0B\u65B9\u7684\u89C4\u5219\u5E93\u4E2D\u3002").addButton(
      (btn) => btn.setButtonText("\u{1F50D} \u626B\u63CF\u77E5\u8BC6\u5E93\u6807\u7B7E").onClick(async () => {
        await this.plugin.detectAndSyncVaultTags();
        this.display();
      })
    );
    containerEl.createEl("h3", { text: "\u6807\u7B7E\u89C4\u5219\u5E93 (Tag Criteria Library)" });
    containerEl.createEl("p", {
      text: "\u5F53\u524D\u5DF2\u914D\u7F6E\u7684\u76EE\u6807\u6807\u7B7E\u3002\u53EF\u5728\u53F3\u4FA7\u968F\u65F6\u542F\u7528\u6216\u5173\u95ED\u7279\u5B9A\u6807\u7B7E\u7684\u81EA\u52A8\u8BC4\u4F30\u3002",
      cls: "setting-item-description"
    });
    this.plugin.settings.tags.forEach((tag, index) => {
      const tagContainer = containerEl.createDiv({ cls: "jev-setting-tag-box" });
      new import_obsidian3.Setting(tagContainer).setName(`\u6807\u7B7E #${tag.name}`).setDesc(tag.instructions).addToggle(
        (toggle) => toggle.setValue(tag.enabled).onChange(async (val) => {
          this.plugin.settings.tags[index].enabled = val;
          await this.plugin.saveSettings();
        })
      );
    });
    new import_obsidian3.Setting(containerEl).setName("\u6062\u590D\u9ED8\u8BA4\u9A8C\u8BC1\u89C4\u5219\u5E93").setDesc("\u5C06\u6240\u6709\u6807\u7B7E\u5224\u5B9A\u89C4\u5219\u6062\u590D\u4E3A\u9996\u53D1\u9A8C\u8BC1\u901A\u8FC7\u7684 4 \u5927\u57FA\u51C6\u5B9A\u4E49\uFF08\u5F02\u5E38\u68C0\u6D4B\u3001\u793E\u4EA4\u5A92\u4F53\u3001\u8D44\u8BAF\u3001AI\uFF09\u3002").addButton(
      (btn) => btn.setButtonText("\u6062\u590D\u9ED8\u8BA4\u89C4\u5219").onClick(async () => {
        this.plugin.settings.tags = JSON.parse(JSON.stringify(DEFAULT_TAG_DEFINITIONS));
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/tagSuggestModal.ts
var import_obsidian4 = require("obsidian");
var TagSuggestModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, file) {
    super(app);
    this.plugin = plugin;
    this.file = file;
    this.results = [];
    this.existingTags = /* @__PURE__ */ new Set();
    this.isLoading = true;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("jev-tagger-modal");
    const header = contentEl.createDiv({ cls: "jev-tagger-header" });
    header.createEl("h3", { text: `\u{1F3F7}\uFE0F Smart Tagger: ${this.file.basename}` });
    header.createEl("div", {
      cls: "jev-tagger-subtitle",
      text: "\u6B63\u5728\u5411 Jev System-1 \u51B3\u7B56\u6A21\u578B\u83B7\u53D6\u6BEB\u79D2\u7EA7\u6807\u7B7E\u7F6E\u4FE1\u5EA6\u5206\u6790..."
    });
    const loadingEl = contentEl.createDiv({ cls: "jev-loading-container" });
    loadingEl.createDiv({ cls: "jev-spinner" });
    loadingEl.createEl("span", { text: "AI \u51B3\u7B56\u5206\u6790\u4E2D..." });
    await this.readExistingTags();
    try {
      this.results = await this.plugin.evaluateFile(this.file);
      this.isLoading = false;
      this.renderResults();
    } catch (error) {
      loadingEl.empty();
      loadingEl.createEl("div", {
        cls: "setting-item-description",
        text: `\u274C \u5206\u6790\u5931\u8D25: ${error.message || error}`
      });
      new import_obsidian4.Notice(`Smart Tagger \u9884\u6D4B\u51FA\u9519: ${error.message || error}`);
    }
  }
  async readExistingTags() {
    const cache = this.app.metadataCache.getFileCache(this.file);
    if (cache?.frontmatter?.tags) {
      const raw = cache.frontmatter.tags;
      if (Array.isArray(raw)) {
        raw.forEach((t) => this.existingTags.add(String(t).replace(/^#/, "")));
      } else if (typeof raw === "string") {
        raw.split(/[\s,]+/).forEach((t) => this.existingTags.add(t.replace(/^#/, "")));
      }
    }
  }
  renderResults() {
    const { contentEl } = this;
    contentEl.empty();
    const header = contentEl.createDiv({ cls: "jev-tagger-header" });
    header.createEl("h3", { text: `\u{1F3F7}\uFE0F Smart Tagger: ${this.file.basename}` });
    const thresholdPct = Math.round(this.plugin.settings.confidenceThreshold * 100);
    header.createEl("div", {
      cls: "jev-tagger-subtitle",
      text: `\u63A8\u8350\u7F6E\u4FE1\u5EA6\u9608\u503C \u2265 ${thresholdPct}%\u3002\u70B9\u51FB\u6309\u94AE\u5373\u53EF\u5B89\u5168\u5199\u5165\u7B14\u8BB0 Frontmatter\u3002`
    });
    const tagList = contentEl.createDiv({ cls: "jev-tag-list" });
    if (this.results.length === 0) {
      tagList.createDiv({
        cls: "setting-item-description",
        text: "\u672A\u68C0\u6D4B\u5230\u7B26\u5408\u5F53\u524D\u7F6E\u4FE1\u5EA6\u9608\u503C\u7684\u6807\u7B7E\u3002"
      });
    } else {
      this.results.forEach((res) => {
        const isExisting = this.existingTags.has(res.tagName);
        const isHighConf = res.probability >= this.plugin.settings.confidenceThreshold;
        const item = tagList.createDiv({ cls: "jev-tag-item" });
        const info = item.createDiv({ cls: "jev-tag-info" });
        const nameRow = info.createDiv({ cls: "jev-tag-name-row" });
        nameRow.createEl("span", { cls: "jev-tag-badge", text: `#${res.tagName}` });
        if (isExisting) {
          nameRow.createEl("span", { cls: "jev-tag-existing", text: "(\u5DF2\u6253\u6807)" });
        }
        info.createEl("div", { cls: "jev-tag-desc", text: res.description });
        const progressContainer = info.createDiv({ cls: "jev-progress-bar-container" });
        const pct = Math.round(res.probability * 100);
        const fill = progressContainer.createDiv({ cls: "jev-progress-bar-fill" });
        fill.style.width = `${pct}%`;
        if (pct >= 80) fill.style.backgroundColor = "var(--color-green, #10b981)";
        else if (pct >= 60) fill.style.backgroundColor = "var(--color-blue, #3b82f6)";
        else fill.style.backgroundColor = "var(--color-yellow, #f59e0b)";
        const right = item.createDiv({ cls: "jev-tag-actions", attr: { style: "display: flex; align-items: center; gap: 10px;" } });
        right.createEl("span", { cls: "jev-confidence-score", text: `${pct}%` });
        if (!isExisting) {
          const addBtn = right.createEl("button", {
            cls: "mod-cta jev-btn-add",
            text: "+ \u6DFB\u52A0"
          });
          addBtn.onclick = async () => {
            await this.addTagToNote(res.tagName);
            this.existingTags.add(res.tagName);
            this.renderResults();
          };
        }
      });
    }
    const footer = contentEl.createDiv({ cls: "jev-actions-footer" });
    const highConfNewTags = this.results.filter((r) => r.probability >= this.plugin.settings.confidenceThreshold && !this.existingTags.has(r.tagName)).map((r) => r.tagName);
    if (highConfNewTags.length > 0) {
      const applyAllBtn = footer.createEl("button", {
        cls: "mod-cta",
        text: `\u26A1 \u4E00\u952E\u5E94\u7528\u6240\u6709\u9AD8\u7F6E\u4FE1\u6807\u7B7E (${highConfNewTags.length}\u4E2A)`
      });
      applyAllBtn.onclick = async () => {
        for (const tag of highConfNewTags) {
          await this.addTagToNote(tag);
          this.existingTags.add(tag);
        }
        new import_obsidian4.Notice(`\u5DF2\u6210\u529F\u6DFB\u52A0 ${highConfNewTags.length} \u4E2A\u6807\u7B7E\u5230 Frontmatter\uFF01`);
        this.close();
      };
    }
    const closeBtn = footer.createEl("button", { text: "\u5173\u95ED" });
    closeBtn.onclick = () => this.close();
  }
  async addTagToNote(tagName) {
    await this.plugin.addTagToFile(this.file, tagName);
    new import_obsidian4.Notice(`\u5DF2\u6DFB\u52A0\u6807\u7B7E #${tagName}`);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var JevTaggerPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.jevClient = new JevClient(this.settings.apiKey, this.settings.endpoint);
    this.addRibbonIcon("tags", "Smart Tagger: \u667A\u80FD\u6807\u7B7E\u63A8\u8350", (evt) => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        new TagSuggestModal(this.app, this, activeFile).open();
      } else {
        new import_obsidian5.Notice("\u8BF7\u5148\u5728\u7F16\u8F91\u5668\u4E2D\u6253\u5F00\u4E00\u7BC7\u7B14\u8BB0\u3002");
      }
    });
    this.addCommand({
      id: "jev-suggest-tags",
      name: "\u4E3A\u5F53\u524D\u6D3B\u52A8\u7B14\u8BB0\u63A8\u8350\u6807\u7B7E (Suggest Tags for Active Note)",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            new TagSuggestModal(this.app, this, activeFile).open();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "jev-auto-apply-tags",
      name: "\u4E00\u952E\u81EA\u52A8\u5E94\u7528\u9AD8\u7F6E\u4FE1\u6807\u7B7E\u5230\u5F53\u524D\u7B14\u8BB0 (Auto-apply Tags to Active Note)",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            this.autoApplyTags(activeFile);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "jev-batch-tag-all",
      name: "\u4E00\u952E\u4E3A\u6240\u6709\u7B14\u8BB0\u626B\u63CF\u5E76\u6DFB\u52A0\u9AD8\u7F6E\u4FE1\u6807\u7B7E (Batch Tag All Notes in Vault)",
      callback: () => {
        new BatchTagModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "jev-sync-vault-tags",
      name: "\u81EA\u52A8\u68C0\u6D4B\u5E76\u540C\u6B65\u77E5\u8BC6\u5E93\u6807\u7B7E\u5E93 (Detect and Sync Vault Tags)",
      callback: async () => {
        await this.detectAndSyncVaultTags();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian5.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("Smart Tagger: \u667A\u80FD\u6807\u7B7E\u63A8\u8350").setIcon("tags").onClick(() => {
              new TagSuggestModal(this.app, this, file).open();
            });
          });
        }
      })
    );
    this.addSettingTab(new JevTaggerSettingTab(this.app, this));
    console.log("Smart Tagger plugin loaded.");
  }
  onunload() {
    console.log("Smart Tagger plugin unloaded.");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.jevClient) {
      this.jevClient.setApiKey(this.settings.apiKey);
    }
  }
  /**
   * Extracts clean state for Jev System-1 model evaluation
   */
  async buildNoteState(file) {
    const rawContent = await this.app.vault.read(file);
    let text = rawContent.replace(/^---[\s\S]*?---\s*/, "");
    text = text.replace(/(^|\s)#[^\s#]+/g, "$1").trim();
    const title = file.basename;
    const introduction = text.slice(0, 450);
    const headings = [];
    const headingMatches = text.match(/^#{1,4}\s+(.+)$/gm);
    if (headingMatches) {
      for (const h of headingMatches.slice(0, 8)) {
        headings.push(h.replace(/^#{1,4}\s+/, "").trim());
      }
    }
    let excerpt = "";
    if (text.length > 700) {
      excerpt = text.slice(-260);
    }
    const state = {
      title,
      headings,
      content_start: introduction,
      content_excerpt: excerpt
    };
    if (text.length < 300) {
      const folder = file.parent ? file.parent.path : "";
      state["folder_context"] = `Folder location: ${folder}`;
    }
    return state;
  }
  /**
   * Calls Jev to evaluate the note against enabled tags
   */
  async evaluateFile(file) {
    const state = await this.buildNoteState(file);
    return await this.jevClient.evaluateNote(state, this.settings.tags);
  }
  /**
   * Auto applies tags that meet the threshold
   */
  async autoApplyTags(file) {
    new import_obsidian5.Notice(`Jev \u6B63\u5728\u5206\u6790\u7B14\u8BB0: ${file.basename}...`);
    try {
      const results = await this.evaluateFile(file);
      const eligible = results.filter((r) => r.probability >= this.settings.confidenceThreshold);
      if (eligible.length === 0) {
        new import_obsidian5.Notice(`\u672A\u68C0\u6D4B\u5230\u7F6E\u4FE1\u5EA6 \u2265 ${Math.round(this.settings.confidenceThreshold * 100)}% \u7684\u65B0\u6807\u7B7E\u3002`);
        return;
      }
      let addedCount = 0;
      for (const res of eligible) {
        const added = await this.addTagToFile(file, res.tagName);
        if (added) addedCount++;
      }
      if (addedCount > 0) {
        new import_obsidian5.Notice(`\u5DF2\u6210\u529F\u81EA\u52A8\u8FFD\u52A0 ${addedCount} \u4E2A\u9AD8\u7F6E\u4FE1\u6807\u7B7E\uFF01`);
      } else {
        new import_obsidian5.Notice(`\u76F8\u5173\u6807\u7B7E\u5747\u5DF2\u5B58\u5728\u4E8E\u7B14\u8BB0\u4E2D\u3002`);
      }
    } catch (e) {
      new import_obsidian5.Notice(`\u81EA\u52A8\u6253\u6807\u5931\u8D25: ${e.message || e}`);
    }
  }
  /**
   * Safely adds tag to frontmatter using Obsidian's processFrontMatter API
   */
  async addTagToFile(file, newTag) {
    let modified = false;
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      let currentTags = [];
      if (frontmatter.tags) {
        if (Array.isArray(frontmatter.tags)) {
          currentTags = frontmatter.tags.map((t) => String(t).replace(/^#/, ""));
        } else if (typeof frontmatter.tags === "string") {
          currentTags = frontmatter.tags.split(/[\s,]+/).map((t) => t.replace(/^#/, ""));
        }
      }
      if (!currentTags.includes(newTag)) {
        currentTags.push(newTag);
        modified = true;
      }
      if (this.settings.autoAddParentAiTag && (newTag === "\u5F02\u5E38\u68C0\u6D4B" || newTag === "Agent" || newTag === "\u6A21\u578B") && !currentTags.includes("AI")) {
        currentTags.push("AI");
        modified = true;
      }
      frontmatter.tags = currentTags;
    });
    return modified;
  }
  /**
   * Detects all tags present in the current Obsidian Vault using metadataCache
   * and syncs them into the plugin's tag library.
   */
  async detectAndSyncVaultTags() {
    const allTagsMap = this.app.metadataCache.getTags();
    const tagKeys = Object.keys(allTagsMap);
    if (tagKeys.length === 0) {
      new import_obsidian5.Notice("\u672A\u5728\u77E5\u8BC6\u5E93\u4E2D\u68C0\u6D4B\u5230\u5DF2\u6709\u6807\u7B7E\u3002");
      return { added: 0, total: 0 };
    }
    let addedCount = 0;
    const existingNames = new Set(this.settings.tags.map((t) => t.name));
    const sortedTags = tagKeys.map((rawTag) => ({
      name: rawTag.replace(/^#/, "").trim(),
      count: allTagsMap[rawTag]
    })).filter((t) => t.name.length > 0 && !t.name.includes("/")).sort((a, b) => b.count - a.count);
    for (const t of sortedTags) {
      if (!existingNames.has(t.name)) {
        this.settings.tags.push({
          name: t.name,
          instructions: `Is this note primarily about ${t.name}?`,
          matchCriteria: `${t.name} and related topics.`,
          otherCriteria: "Other topics.",
          enabled: true
        });
        existingNames.add(t.name);
        addedCount++;
      }
    }
    await this.saveSettings();
    new import_obsidian5.Notice(`\u{1F3F7}\uFE0F \u6807\u7B7E\u5E93\u68C0\u6D4B\u5B8C\u6210\uFF01\u5171\u626B\u63CF\u5230 ${sortedTags.length} \u4E2A\u5DF2\u6709\u6807\u7B7E\uFF0C\u81EA\u52A8\u65B0\u53D1\u73B0\u5E76\u540C\u6B65 ${addedCount} \u4E2A\u65B0\u6807\u7B7E\u81F3\u89C4\u5219\u5E93\uFF01`);
    return { added: addedCount, total: sortedTags.length };
  }
};
